Feature/button-fixed-layout
Telefonica-Hispanoamerica/kenos-native pull request #37
Opened 2024-03-01 23:19 UTC by jlr03

2024-03-02 03:01 UTC, eeuruetade requested changes

2024-03-02 03:01 UTC, eeuruetade commented on src/components/LayoutButton/ButtonFixedFooter.Type.tsx
Crear las subcarpetas correspondientes para cada layout ButtonFixedFooter, ButtonLayout, IconButtonLayout y crear un archivo index.ts como archivo de barril para exportar todos los componentes

2024-03-04 13:22 UTC, jlr03 commented on src/components/LayoutButton/ButtonFixedFooter.css.tsx
Se actualiza el css con los colores proporcionados por la skin

2024-03-04 13:23 UTC, jlr03 commented on src/components/LayoutButton/ButtonFixedFooter.Type.tsx
Se organizan los componentes layout como archivo de barrill

2024-03-06 20:14 UTC, eeuruetade approved these changes

2024-03-06 20:14 UTC, merged